<a href="https://colab.research.google.com/github/Andrei198203/Data_Science_HW_1/blob/main/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Creating a vector with the first 10 positive integers
vector = np.arange(1, 11)

# Vector values
print("Vector with first 10 positive integers:", vector)

Вектор з першими 10 натуральними числами: [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
import numpy as np

# Creating 3x3 matrix filled with zeros
matrix = np.zeros((3, 3))

# Output of matrix values
print("A two-dimensional array (matrix) of size 3x3 with zeros:")
print(matrix)

A two-dimensional array (matrix) of size 3x3 with zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
import numpy as np

# Create 5x5 array filled with random integers in the range from 1 to 10
matrix = np.random.randint(1, 11, size=(5, 5))

# Displaying the values of an array
print("An array of size 5x5 with random integers from 1 to 10:")
print(matrix)

An array of size 5x5 with random integers from 1 to 10:
[[ 4 10  8  3  8]
 [ 1  4  8  1  6]
 [ 2  7  3 10  8]
 [ 4  5  5  2  9]
 [ 1  8  6  2  7]]


In [5]:
import numpy as np

# Creating an array of size 4x4 filled with random real numbers in the range from 0 to 1
matrix = np.random.rand(4, 4)

# Outputting array values
print("Array of size 4x4 with random real numbers in the range from 0 to 1:")
print(matrix)

Array of size 4x4 with random real numbers in the range from 0 to 1:
[[0.87549665 0.1925006  0.0903562  0.61680765]
 [0.86644721 0.50053857 0.92069306 0.27246952]
 [0.18507738 0.16393665 0.15579546 0.40488507]
 [0.33929938 0.8128249  0.16214668 0.48262148]]
