<a href="https://colab.research.google.com/github/Andrei198203/Data_Science_HW_1/blob/main/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Creating a vector with the first 10 positive integers
vector = np.arange(1, 11)

# Vector values
print("Vector with first 10 positive integers:", vector)

Вектор з першими 10 натуральними числами: [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
import numpy as np

# Creating 3x3 matrix filled with zeros
matrix = np.zeros((3, 3))

# Output of matrix values
print("A two-dimensional array (matrix) of size 3x3 with zeros:")
print(matrix)

A two-dimensional array (matrix) of size 3x3 with zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
import numpy as np

# Create 5x5 array filled with random integers in the range from 1 to 10
matrix = np.random.randint(1, 11, size=(5, 5))

# Displaying the values of an array
print("An array of size 5x5 with random integers from 1 to 10:")
print(matrix)

An array of size 5x5 with random integers from 1 to 10:
[[7 4 7 1 9]
 [2 1 4 8 2]
 [4 6 2 2 7]
 [4 1 6 3 5]
 [5 1 1 3 4]]
