<a href="https://colab.research.google.com/github/Andrei198203/Data_Science_HW_1/blob/main/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1

In [ ]:
import numpy as np

# Creating a vector with the first 10 positive integers
vector = np.arange(1, 11)

# Vector values
print("Vector with first 10 positive integers:", vector)

Вектор з першими 10 натуральними числами: [ 1  2  3  4  5  6  7  8  9 10]


Task 2

In [ ]:
import numpy as np

# Creating 3x3 matrix filled with zeros
matrix = np.zeros((3, 3))

# Output of matrix values
print("A two-dimensional array (matrix) of size 3x3 with zeros:")
print(matrix)

A two-dimensional array (matrix) of size 3x3 with zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Task 3

In [ ]:
import numpy as np

# Create 5x5 array filled with random integers in the range from 1 to 10
matrix = np.random.randint(1, 11, size=(5, 5))

# Displaying the values of an array
print("An array of size 5x5 with random integers from 1 to 10:")
print(matrix)

An array of size 5x5 with random integers from 1 to 10:
[[ 4 10  8  3  8]
 [ 1  4  8  1  6]
 [ 2  7  3 10  8]
 [ 4  5  5  2  9]
 [ 1  8  6  2  7]]


Task 4

In [ ]:
import numpy as np

# Creating an array of size 4x4 filled with random real numbers in the range from 0 to 1
matrix = np.random.rand(4, 4)

# Outputting array values
print("Array of size 4x4 with random real numbers in the range from 0 to 1:")
print(matrix)

Array of size 4x4 with random real numbers in the range from 0 to 1:
[[0.87549665 0.1925006  0.0903562  0.61680765]
 [0.86644721 0.50053857 0.92069306 0.27246952]
 [0.18507738 0.16393665 0.15579546 0.40488507]
 [0.33929938 0.8128249  0.16214668 0.48262148]]


Task 5

In [ ]:
import numpy as np

# Creating two random arrays of size 5 with integers from 1 to 10
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

# Outputting the created arrays
print("The first array:", array1)
print("The second array:", array2)

# Performing elementary addition
addition_result = np.add(array1, array2)
print("The result of addition:", addition_result)

# Performing elementary subtraction
subtraction_result = np.subtract(array1, array2)
print("The result of subtraction:", subtraction_result)

# Performing elementary multiplication
multiplication_result = np.multiply(array1, array2)
print("The result of multiplication:", multiplication_result)

The first array: [9 6 1 9 6]
The second array: [10  2  9  4  6]
The result of addition: [19  8 10 13 12]
The result of subtraction: [-1  4 -8  5  0]
The result of multiplication: [90 12  9 36 36]


Task 6

In [ ]:
import numpy as np

# Create two vectors of size 7 filled with arbitrary numbers
vector1 = np.random.randint(1, 10, size=7)
vector2 = np.random.randint(1, 10, size=7)

# Display the two vectors
print("First vector:", vector1)
print("Second vector:", vector2)

# Calculate the scalar product (dot product) of the two vectors
scalar_product = np.dot(vector1, vector2)

# Display the scalar product
print("Scalar product (dot product) of the two vectors:", scalar_product)

First vector: [4 4 9 3 7 2 8]
Second vector: [4 1 9 5 4 5 8]
Scalar product (dot product) of the two vectors: 218


Task 7

In [ ]:
import numpy as np

# Create two matrices of size 2x2 and 2x3 filled with random integers
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

# Display the two matrices
print("First matrix:\n", matrix1)
print("Second matrix:\n", matrix2)

# Multiply the two matrices
result = np.dot(matrix1, matrix2)

# Display the result
print("Result of multiplying the two matrices:\n", result)

First matrix:
 [[6 7]
 [9 3]]
Second matrix:
 [[6 1 6]
 [7 2 2]]
Result of multiplying the two matrices:
 [[85 20 50]
 [75 15 60]]


Task 8

In [ ]:
import numpy as np

# Create a 3x3 matrix filled with random integers
matrix = np.random.randint(1, 11, size=(3, 3))

# Display the matrix
print("Original matrix:\n", matrix)

# Check if the matrix is invertible
if np.linalg.det(matrix) != 0:
    # If the matrix is invertible, find its inverse matrix
    inverse_matrix = np.linalg.inv(matrix)
    # Display the inverse matrix
    print("Inverse matrix:\n", inverse_matrix)
else:
    print("The matrix is not invertible.")

Original matrix:
 [[ 3  9  2]
 [ 4  7 10]
 [ 1  4  6]]
Inverse matrix:
 [[-0.01960784  0.45098039 -0.74509804]
 [ 0.1372549  -0.15686275  0.21568627]
 [-0.08823529  0.02941176  0.14705882]]


Task 9

In [ ]:
import numpy as np

# Create a 4x4 matrix filled with random real numbers in the range from 0 to 1
matrix = np.random.rand(4, 4)

# Display the original matrix
print("Original matrix:\n", matrix)

# Transpose the matrix
transposed_matrix = np.transpose(matrix)

# Display the transposed matrix
print("Transposed matrix:\n", transposed_matrix)

Original matrix:
 [[0.18083948 0.11399113 0.79622039 0.27505816]
 [0.28958444 0.42961294 0.94421478 0.2251888 ]
 [0.74313571 0.33204469 0.99909568 0.13341234]
 [0.5175905  0.28556992 0.32927014 0.48665508]]
Transposed matrix:
 [[0.18083948 0.28958444 0.74313571 0.5175905 ]
 [0.11399113 0.42961294 0.33204469 0.28556992]
 [0.79622039 0.94421478 0.99909568 0.32927014]
 [0.27505816 0.2251888  0.13341234 0.48665508]]


Task 10

In [ ]:
import numpy as np

# Create a 3x4 matrix filled with random integers in the range from 1 to 10
matrix = np.random.randint(1, 11, size=(3, 4))

# Create a vector of size 4 filled with random integers in the range from 1 to 10
vector = np.random.randint(1, 11, size=4)

# Display the matrix and the vector
print("Matrix:\n", matrix)
print("Vector:", vector)

# Multiply the matrix by the vector
result = np.dot(matrix, vector)

# Display the result
print("Result of multiplying the matrix by the vector:", result)

Matrix:
 [[7 5 7 9]
 [7 8 4 1]
 [4 4 1 7]]
Vector: [3 7 6 6]
Result of multiplying the matrix by the vector: [152 107  88]


Task 11

In [ ]:
import numpy as np

# Create a 2x3 matrix filled with random real numbers in the range from 0 to 1
matrix = np.random.rand(2, 3)

# Create a vector of size 3 filled with random real numbers in the range from 0 to 1
vector = np.random.rand(3)

# Display the matrix and the vector
print("Matrix:\n", matrix)
print("Vector:", vector)

# Multiply the matrix by the vector
result = np.dot(matrix, vector)

# Display the result
print("Result of multiplying the matrix by the vector:", result)

Matrix:
 [[0.46954925 0.83093762 0.73730173]
 [0.59379356 0.99280734 0.45706144]]
Vector: [0.22800605 0.45219358 0.71423762]
Result of multiplying the matrix by the vector: [1.00941336 0.9107801 ]


Task 12

In [ ]:
import numpy as np

# Create two matrices of size 2x2 filled with random integers in the range from 1 to 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Display the two matrices
print("First matrix:\n", matrix1)
print("Second matrix:\n", matrix2)

# Perform elementwise multiplication of the two matrices
result = np.multiply(matrix1, matrix2)

# Display the result
print("Elementwise multiplication of the two matrices:\n", result)

First matrix:
 [[8 9]
 [2 2]]
Second matrix:
 [[ 6 10]
 [ 8  8]]
Elementwise multiplication of the two matrices:
 [[48 90]
 [16 16]]


Task 13

In [ ]:
import numpy as np

# Create two matrices of size 2x2 filled with random integers in the range from 1 to 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Display the two matrices
print("First matrix:\n", matrix1)
print("Second matrix:\n", matrix2)

# Find the product of the two matrices
result = np.dot(matrix1, matrix2)

# Display the result
print("Product of the two matrices:\n", result)

First matrix:
 [[8 3]
 [6 8]]
Second matrix:
 [[ 1  5]
 [10  8]]
Product of the two matrices:
 [[38 64]
 [86 94]]


Task 14

In [ ]:
import numpy as np

# Create a 5x5 matrix filled with random integers in the range from 1 to 100
matrix = np.random.randint(1, 101, size=(5, 5))

# Display the matrix
print("Matrix:\n", matrix)

# Find the sum of the matrix elements
sum_of_elements = np.sum(matrix)

# Display the sum of the matrix elements
print("Sum of the matrix elements:", sum_of_elements)

Matrix:
 [[ 80  72  17   8  42]
 [ 70  70  72  70  25]
 [ 53   5  57   9  67]
 [ 23  58   7   8  60]
 [  2  16  51 100  27]]
Sum of the matrix elements: 1069


Task 15

In [1]:
# Create two matrices of size 4x4 filled with random integers in the range from 1 to 10
import numpy as np
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

# Display the two matrices
print("First matrix:\n", matrix1)
print("Second matrix:\n", matrix2)

# Find the difference between the two matrices
difference = matrix1 - matrix2

# Display the result
print("Difference between the two matrices:\n", difference)

First matrix:
 [[ 6  9  4  7]
 [ 1 10  3  8]
 [ 7 10  1  8]
 [ 4  2  9  1]]
Second matrix:
 [[ 4 10  1  7]
 [10  6  2  6]
 [ 8  1  5  1]
 [ 1  9  8  7]]
Difference between the two matrices:
 [[ 2 -1  3  0]
 [-9  4  1  2]
 [-1  9 -4  7]
 [ 3 -7  1 -6]]


Task 16

In [2]:
import numpy as np

# Create a 3x3 matrix filled with random real numbers in the range from 0 to 1
matrix = np.random.rand(3, 3)

# Display the original matrix
print("Original matrix:\n", matrix)

# Compute the sum of each row
row_sums = np.sum(matrix, axis=1)

# Reshape the row sums into a column vector
column_vector = row_sums.reshape(-1, 1)

# Display the column vector containing the sum of the elements of each row
print("Column vector containing the sum of each row:", column_vector)

Original matrix:
 [[0.38700245 0.59965077 0.80955044]
 [0.39101144 0.32494417 0.53452471]
 [0.86706157 0.80841952 0.57463555]]
Column vector containing the sum of each row: [[1.79620366]
 [1.25048032]
 [2.25011665]]


Task 17

In [3]:
import numpy as np

# Create a 3x4 matrix with any integers
original_matrix = np.array([[1, 2, 3, 4],
                            [5, 6, 7, 8],
                            [9, 10, 11, 12]])

# Display the original matrix
print("Original matrix:\n", original_matrix)

# Compute the element-wise square of each number
squared_matrix = np.square(original_matrix)

# Display the matrix with the squares
print("Matrix with the squares of the numbers:\n", squared_matrix)

Original matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Matrix with the squares of the numbers:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


Task 18

In [4]:
import numpy as np

# Create a vector of size 4 filled with random integers in the range from 1 to 50
original_vector = np.random.randint(1, 51, size=4)

# Display the original vector
print("Original vector:", original_vector)

# Compute the square roots of the numbers in the vector
sqrt_vector = np.sqrt(original_vector)

# Display the vector with the square roots
print("Vector with the square roots of the numbers:", sqrt_vector)

Original vector: [29  7 41  7]
Vector with the square roots of the numbers: [5.38516481 2.64575131 6.40312424 2.64575131]
